これはどう
tignear/node-openjtalk-binding pull request #4
Opened 2021-06-17 23:23 UTC by Sueqkjs

falsyな値を全て弾いて見た

2021-06-28 15:41 UTC, tignear commented
majorっぽいなぁ

2021-06-28 15:44 UTC, tignear commented
あ。これだめ。

2021-06-28 15:46 UTC, tignear requested changes

2021-06-28 15:46 UTC, tignear commented on addon.js
> +  if (!text) throw new TypeError("The first argument must be a non-empty string");
直接例外投げないで。

2021-06-28 15:51 UTC, tignear commented
メモ:  
エラーの一貫性(ほかのSynthesis failedのパターンをどう考えるか)よりも早期に弾けるエラーを弾くことを優先すべきなのでこのPRは妥当。

2021-06-28 15:58 UTC, tignear commented
majoirじゃねぇやw

2021-06-28 22:44 UTC, Sueqkjs commented on addon.js
> +  if (!text) throw new TypeError("The first argument must be a non-empty string");
確かに…見落としていた…

2021-06-29 09:43 UTC, tignear approved these changes

2021-06-29 09:43 UTC, tignear commented
満足ならreadyにしてもらえればー

2021-06-30 08:32 UTC, Sueqkjs commented
しました！

2021-06-30 10:33 UTC, merged